import pluginReplace from '@rollup/plugin-replace';
import type { RollupReplaceOptions } from '@rollup/plugin-replace';

function iconsReplace(opts: RollupReplaceOptions) {
	return pluginReplace({
		...opts,
		preventAssignment: false,
		// only replace these strings at the start of strings, and make
		// sure they're followed by a word-boundary that's not a dash
		delimiters: ['(?<=["\'`])', '\\b(?!-)'],
	});
}

export function pluginReplaceIcons() {
	return [
			iconsReplace({
				values: {
					'ti ti-alert-triangle': 'ph ph-warning ph-bold ph-lg',
				},
				exclude: [
					'**/components/MkAnnouncementDialog.*',
					'**/pages/announcement.*',
				],
			}),
			iconsReplace({
				values: {
					'ti ti-alert-triangle': 'ph ph-warning-circle ph-bold ph-lg',
				},
				include: [
					'**/components/MkAnnouncementDialog.*',
					'**/pages/announcement.*',
				],
			}),
			iconsReplace({
				values: {
					'ti ti-apps': 'ph ph-squares-four ph-bold ph-lg',
				},
				include: [
					'**/pages/**',
				],
			}),
			iconsReplace({
				values: {
					'ti ti-apps': 'ph ph-stack ph-bold ph-lg',
				},
				include: [
					'**/ui/**',
				],
			}),
			iconsReplace({
				values: {
					'ti ti-clock-play': 'ph ph-clock ph-bold ph-lg',
				},
				exclude: [
					'**/components/MkMedia*',
				],
			}),
			iconsReplace({
				values: {
					'ti ti-clock-play': 'ph ph-gauge ph-bold ph-lg',
				},
				include: [
					'**/components/MkMedia*',
				],
			}),
			iconsReplace({
				values: {
					'ti ti-photo': 'ph ph-image-square ph-bold ph-lg',
				},
				exclude: [
					'**/pages/admin-user.*',
				],
			}),
			iconsReplace({
				values: {
					'ti ti-photo': 'ph ph-image ph-bold ph-lg',
				},
				include: [
					'**/pages/admin-user.*',
				],
			}),
			iconsReplace({
				values: {
					'ti ti-reload': 'ph ph-arrow-clockwise ph-bold ph-lg',
				},
				exclude: [
					'**/pages/settings/emoji-picker.*',
					'**/pages/flash/flash.*',
					'**/components/MkPageWindow.*',
				],
			}),
			iconsReplace({
				values: {
					'ti ti-reload': 'ph ph-arrow-counter-clockwise ph-bold ph-lg',
				},
				include: [
					'**/pages/settings/emoji-picker.*',
				],
			}),
			iconsReplace({
				values: {
					'ti ti-reload': 'ph ph-arrows-clockwise ph-bold ph-lg',
				},
				include: [
					'**/pages/flash/flash.*',
					'**/components/MkPageWindow.*',
				],
			}),
			iconsReplace({
				values: {
					'ti ti-repeat': 'ph ph-rocket-launch ph-bold ph-lg',
				},
				exclude: [
					'**/components/MkMedia*',
					'**/scripts/get-user-menu.*',
					'**/pages/gallery/post.*',
				],
			}),
			iconsReplace({
				values: {
					'ti ti-repeat': 'ph ph-repeat ph-bold ph-lg',
				},
				include: [
					'**/components/MkMedia*',
					'**/scripts/get-user-menu.*',
					'**/pages/gallery/post.*',
				],
			}),
			iconsReplace({
				values: {
					'icon ti ti-brand-youtube': 'icon ph ph-youtube-logo ph-bold ph-lg',
					'ti ti-123': 'ph ph-numpad ph-bold ph-lg',
					'ti ti-access-point': 'ph ph-broadcast ph-bold ph-lg',
					'ti ti-activity': 'ph ph-pulse ph-bold ph-lg',
					'ti ti-ad': 'ph ph-flag ph-bold ph-lg',
					'ti ti-adjustments': 'ph ph-faders ph-bold ph-lg',
					'ti ti-align-box-left-bottom': 'ph ph-arrow-down-left ph-bold ph-lg',
					'ti ti-align-box-left-top': 'ph ph-arrow-up-left ph-bold ph-lg',
					'ti ti-align-box-right-bottom': 'ph ph-arrow-down-right ph-bold ph-lg',
					'ti ti-align-box-right-top': 'ph ph-arrow-up-right ph-bold ph-lg',
					'ti ti-align-left': 'ph ph-text-align-left ph-bold ph-lg',
					'ti ti-antenna': 'ph ph-flying-saucer ph-bold ph-lg',
					'ti ti-api': 'ph ph-key ph-bold ph-lg',
					'ti ti-app-window': 'ph ph-app-window ph-bold ph-lg',
					'ti ti-apple': 'ph ph-orange-slice ph-bold ph-lg',
					'ti ti-arrow-back-up': 'ph ph-arrow-u-up-left ph-bold ph-lg',
					'ti ti-arrow-bar-to-down': 'ph ph-arrow-line-down ph-bold ph-lg',
					'ti ti-arrow-big-right': 'ph ph-arrow-fat-right ph-bold ph-lg',
					'ti ti-arrow-down': 'ph ph-arrow-down ph-bold ph-lg',
					'ti ti-arrow-left': 'ph ph-arrow-left ph-bold ph-lg',
					'ti ti-arrow-narrow-up': 'ph ph-arrow-up ph-bold ph-lg',
					'ti ti-arrow-right': 'ph ph-arrow-right ph-bold ph-lg',
					'ti ti-arrow-up': 'ph ph-arrow-up ph-bold ph-lg',
					'ti ti-arrows-maximize': 'ph ph-arrows-out ph-bold ph-lg',
					'ti ti-arrows-minimize': 'ph ph-arrows-in ph-bold ph-lg',
					'ti ti-arrows-move': 'ph ph-arrows-out-cardinal ph-bold ph-lg',
					'ti ti-arrows-sort': 'ph ph-arrows-down-up ph-bold ph-lg',
					'ti ti-arrows-up': 'ph ph-arrow-line-up ph-bold ph-lg',
					'ti ti-asterisk': 'ph ph-asterisk ph-bold ph-lg',
					'ti ti-at': 'ph ph-at ph-bold ph-lg',
					'ti ti-backspace': 'ph ph-backspace ph-bold ph-lg',
					'ti ti-badge': 'ph ph-seal-check ph-bold ph-lg',
					'ti ti-badges': 'ph ph-seal-check ph-bold ph-lg',
					'ti ti-ban': 'ph ph-prohibit ph-bold ph-lg',
					'ti ti-bell': 'ph ph-bell ph-bold ph-lg',
					'ti ti-bell-off': 'ph ph-bell ph-bold ph-lg',
					'ti ti-bell-plus': 'ph ph-bell-ringing ph-bold ph-lg',
					'ti ti-bell-ringing-2': 'ph ph-bell-ringing ph-bold ph-lg',
					'ti ti-bolt': 'ph ph-lightning ph-bold ph-lg',
					'ti ti-bookmark': 'ph ph-bookmark ph-bold ph-lg',
					'ti ti-brand-x': 'ph ph-twitter-logo ph-bold ph-lg',
					'ti ti-bulb': 'ph ph-libghtbulb ph-bold ph-lg',
					'ti ti-cake': 'ph ph-cake ph-bold ph-lg',
					'ti ti-calendar': 'ph ph-calendar ph-bold ph-lg',
					'ti ti-calendar-time': 'ph ph-calendar ph-bold ph-lg',
					'ti ti-camera': 'ph ph-camera ph-bold ph-lg',
					'ti ti-carousel-horizontal': 'ph ph-split-horizontal ph-bold ph-lg',
					'ti ti-carousel-vertical': 'ph ph-split-vertical ph-bold ph-lg',
					'ti ti-chart-arrows': 'ph ph-chart-bar-horizontal ph-bold ph-lg',
					'ti ti-chart-line': 'ph ph-chart-line ph-bold ph-lg',
					'ti ti-check': 'ph ph-check ph-bold ph-lg',
					'ti ti-checkbox': 'ph ph-check ph-bold ph-lg',
					'ti ti-checklist': 'ph ph-list-checks ph-bold ph-lg',
					'ti ti-checkup-list': 'ph ph-list-checks ph-bold ph-lg',
					'ti ti-chevron-double-right': 'ph ph-caret-double-right ph-bold ph-lg',
					'ti ti-chevron-left': 'ph ph-caret-left ph-bold ph-lg',
					'ti ti-chevron-right': 'ph ph-caret-right ph-bold ph-lg',
					'ti ti-chevron-up': 'ph ph-caret-up ph-bold ph-lg',
					'ti ti-chevrons-left': 'ph ph-caret-dobule-left ph-bold ph-lg',
					'ti ti-chevrons-right': 'ph ph-caret-right ph-bold ph-lg',
					'ti ti-circle': 'ph ph-circle ph-bold ph-lg',
					'ti ti-circle-check': 'ph ph-seal-check ph-bold ph-lg',
					'ti ti-circle-filled': 'ph ph-circle-half ph-bold ph-lg',
					'ti ti-circle-minus': 'ph ph-minus-circle ph-bold ph-lg',
					'ti ti-circle-x': 'ph ph-x-circle ph-bold ph-lg',
					'ti ti-clock': 'ph ph-clock ph-bold ph-lg',
					'ti ti-clock-edit': 'ph ph-pencil-simple ph-bold ph-lg',
					'ti ti-cloud': 'ph ph-cloud ph-bold ph-lg',
					'ti ti-code': 'ph ph-code ph-bold ph-lg',
					'ti ti-columns': 'ph ph-text-columns ph-bold ph-lg',
					'ti ti-comet': 'ph ph-shooting-star ph-bold ph-lg',
					'ti ti-confetti': 'ph ph-confetti ph-bold ph-lg',
					'ti ti-cookie': 'ph ph-cookie ph-bold ph-lg',
					'ti ti-copy': 'ph ph-copy ph-bold ph-lg',
					'ti ti-cpu': 'ph ph-cpu ph-bold ph-lg',
					'ti ti-crop': 'ph ph-crop ph-bold ph-lg',
					'ti ti-crown': 'ph ph-crown ph-bold ph-lg',
					'ti ti-dashboard': 'ph ph-gauge ph-bold ph-lg',
					'ti ti-database': 'ph ph-database ph-bold ph-lg',
					'ti ti-device-desktop': 'ph ph-desktop ph-bold ph-lg',
					'ti ti-device-floppy': 'ph ph-floppy-disk ph-bold ph-lg',
					'ti ti-device-gamepad': 'ph ph-game-controller ph-bold ph-lg',
					'ti ti-device-mobile': 'ph ph-device-mobile ph-bold ph-lg',
					'ti ti-device-tablet': 'ph ph-device-tablet ph-bold ph-lg',
					'ti ti-device-tv': 'ph ph-television ph-bold ph-lg',
					'ti ti-devices': 'ph ph-devices ph-bold ph-lg',
					'ti ti-dice': 'ph ph-dice-five ph-bold ph-lg',
					'ti ti-dice-5': 'ph ph-dice-five ph-bold ph-lg',
					'ti ti-dots': 'ph ph-dots-three ph-bold ph-lg',
					'ti ti-download': 'ph ph-download ph-bold ph-lg',
					'ti ti-edit': 'ph ph-pencil-simple-line ph-bold ph-lg',
					'ti ti-equal-double': 'ph ph-equals ph-bold ph-lg',
					'ti ti-equal-not': 'ph ph-prohibit ph-bold ph-lg',
					'ti ti-exclamation-circle': 'ph ph-warning-circle ph-bold ph-lg',
					'ti ti-external-link': 'ph ph-arrow-square-out ph-bold ph-lg',
					'ti ti-eye': 'ph ph-eye ph-bold ph-lg',
					'ti ti-eye-exclamation': 'ph ph-eye-slash ph-bold ph-lg',
					'ti ti-eye-off': 'ti ti-eye-exclamation',
					'ti ti-feather': 'ph ph-feather ph-bold ph-lg',
					'ti ti-file': 'ph ph-file ph-bold ph-lg',
					'ti ti-file-invoice': 'ph ph-newspaper-clipping ph-bold ph-lg',
					'ti ti-file-music': 'ph ph-file-audio ph-bold ph-lg',
					'ti ti-file-text': 'ph ph-file-text ph-bold ph-lg',
					'ti ti-file-zip': 'ph ph-file-zip ph-bold ph-lg',
					'ti ti-filter': 'ph ph-funnel ph-bold ph-lg',
					'ti ti-flare': 'ph ph-fire ph-bold ph-lg',
					'ti ti-flask': 'ph ph-flask ph-bold ph-lg',
					'ti ti-folder': 'ph ph-folder ph-bold ph-lg',
					'ti ti-folder-plus': 'ph ph-folder-plus ph-bold ph-lg',
					'ti ti-forms': 'ph ph-textbox ph-bold ph-lg',
					'ti ti-ghost': 'ph ph-ghost ph-bold ph-lg',
					'ti ti-grid-dots': 'ph ph-dots-nine ph-bold ph-lg',
					'ti ti-hash': 'ph ph-hash ph-bold ph-lg',
					'ti ti-heart': 'ph ph-heart ph-bold ph-lg',
					'ti ti-heart-filled': 'ph ph-heart ph-bold ph-lg',
					'ti ti-heart-off': 'ph ph-heart-break ph-bold ph-lg',
					'ti ti-heart-plus': 'ph ph-heart ph-bold ph-lg',
					'ti ti-help-circle': 'ph ph-question ph-bold ph-lg',
					'ti ti-home': 'ph ph-house ph-bold ph-lg',
					'ti ti-hourglass-empty': 'ph ph-hourglass ph-bold ph-lg',
					'ti ti-id': 'ph ph-identification-card ph-bold ph-lg',
					'ti ti-info-circle': 'ph ph-info ph-bold ph-lg',
					'ti ti-key': 'ph ph-key ph-bold ph-lg',
					'ti ti-language-hiragana': 'ph ph-translate ph-bold ph-lg',
					'ti ti-leaf': 'ph ph-leaf ph-bold ph-lg',
					'ti ti-license': 'ph ph-notebook ph-bold ph-lg',
					'ti ti-link': 'ph ph-link ph-bold ph-lg',
					'ti ti-link-off': 'ph ph-link-break ph-bold ph-lg',
					'ti ti-list': 'ph ph-list ph-bold ph-lg',
					'ti ti-list-search': 'ph ph-list ph-bold ph-lg-search',
					'ti ti-lock': 'ph ph-lock ph-bold ph-lg',
					'ti ti-lock-open': 'ph ph-lock-open ph-bold ph-lg',
					'ti ti-mail': 'ph ph-envelope ph-bold ph-lg',
					'ti ti-map-pin': 'ph ph-map-pin ph-bold ph-lg',
					'ti ti-maximize': 'ph ph-frame-corners ph-bold ph-lg',
					'ti ti-medal': 'ph ph-trophy ph-bold ph-lg',
					'ti ti-menu': 'ph ph-list ph-bold ph-lg',
					'ti ti-menu-2': 'ph ph-list ph-bold ph-lg',
					'ti ti-message': 'ph ph-envelope ph-bold ph-lg',
					'ti ti-message-off': 'ph ph-bell-slash ph-bold ph-lg',
					'ti ti-messages': 'ph ph-envelope ph-bold ph-lg',
					'ti ti-messages-off': 'ph ph-envelope-open ph-bold ph-lg',
					'ti ti-minimize': 'ph ph-arrows-in-simple ph-bold ph-lg',
					'ti ti-minus': 'ph ph-minus ph-bold ph-lg',
					'ti ti-mood-happy': 'ph ph-smiley ph-bold ph-lg',
					'ti ti-mood-smile': 'ph ph-smiley ph-bold pg-lg',
					'ti ti-moon': 'ph ph-moon ph-bold ph-lg',
					'ti ti-movie': 'ph ph-film-strip ph-bold ph-lg',
					'ti ti-music': 'ph ph-music-notes ph-bold ph-lg',
					'ti ti-news': 'ph ph-newspaper ph-bold ph-lg',
					'ti ti-note': 'ph ph-note ph-bold ph-lg',
					'ti ti-notebook': 'ph ph-notebook ph-bold ph-lg',
					'ti ti-package': 'ph ph-package ph-bold ph-lg',
					'ti ti-paint': 'ph ph-paint-roller ph-bold ph-lg',
					'ti ti-palette': 'ph ph-palette ph-bold ph-lg',
					'ti ti-paperclip': 'ph ph-paperclip ph-bold ph-lg',
					'ti ti-password': 'ph ph-password ph-bold ph-lg',
					'ti ti-pencil': 'ph ph-pencil-simple ph-bold ph-lg',
					'ti ti-pencil-plus': 'ph ph-plus ph-bold pg-lg',
					'ti ti-photo-plus': 'ph ph-image-square ph-bold ph-lg',
					'ti ti-picture-in-picture': 'ph ph-picture-in-picture ph-bold ph-lg',
					'ti ti-pin': 'ph ph-push-pin ph-bold ph-lg',
					'ti ti-pinned-off': 'ph ph-push-pin-slash ph-bold ph-lg',
					'ti ti-plane': 'ph ph-airplane ph-bold ph-lg',
					'ti ti-plane-arrival': 'ph ph-airplane-landing ph-bold ph-lg',
					'ti ti-plane-departure': 'ph ph-airplane-takeoff ph-bold ph-lg',
					'ti ti-planet': 'ph ph-planet ph-bold ph-lg',
					'ti ti-planet-off': 'ph ph-globe-simple ph-bold ph-lg',
					'ti ti-player-eject': 'ph ph-eject ph-bold ph-lg',
					'ti ti-player-pause': 'ph ph-pause ph-bold ph-lg',
					'ti ti-player-pause-filled': 'ph ph-pause ph-bold ph-lg',
					'ti ti-player-play': 'ph ph-play ph-bold ph-lg',
					'ti ti-player-play-filled': 'ph ph-play ph-bold ph-lg',
					'ti ti-player-stop': 'ph ph-stop ph-bold ph-lg',
					'ti ti-player-track-next': 'ph ph-skip-forward ph-bold ph-lg',
					'ti ti-plug': 'ph ph-plug ph-bold ph-lg',
					'ti ti-plus': 'ph ph-plus ph-bold ph-lg',
					'ti ti-point': 'ph ph-circle ph-bold ph-lg',
					'ti ti-power': 'ph ph-power ph-bold ph-lg',
					'ti ti-presentation': 'ph ph-presentation ph-bold ph-lg',
					'ti ti-quote': 'ph ph-quotes ph-bold ph-lg',
					'ti ti-rectangle': 'ph ph-frame-corners ph-bold ph-lg',
					'ti ti-refresh': 'ph ph-arrows-counter-clockwise ph-bold ph-lg',
					'ti ti-repeat-off': 'ph ph-repeat ph-bold ph-lg',
					'ti ti-robot': 'ph ph-robot ph-bold ph-lg',
					'ti ti-rocket': 'ph ph-rocket-launch ph-bold ph-lg',
					'ti ti-rocket-off': 'ph ph-rocket ph-bold ph-lg',
					'ti ti-rss': 'ph ph-rss ph-bold ph-lg',
					'ti ti-search': 'ph ph-magnifying-glass ph-bold ph-lg',
					'ti ti-section': 'ph ph-selection-all ph-bold ph-lg',
					'ti ti-selector': 'ph ph-caret-up-down ph-bold ph-lg',
					'ti ti-send': 'ph ph-paper-plane-tilt ph-bold ph-lg',
					'ti ti-server': 'ph ph-hard-drives ph-bold ph-lg',
					'ti ti-settings': 'ph ph-gear ph-bold ph-lg',
					'ti ti-share': 'ph ph-share-network ph-bold ph-lg',
					'ti ti-shield': 'ph ph-shield ph-bold ph-lg',
					'ti ti-shield-lock': 'ph ph-shield ph-bold ph-lg',
					'ti ti-snowflake': 'ph ph-snowflake ph-bold ph-lg',
					'ti ti-sparkles': 'ph ph-sparkle ph-bold ph-lg',
					'ti ti-speakerphone': 'ph ph-megaphone ph-bold ph-lg',
					'ti ti-stack-2': 'ph ph-stack ph-bold ph-lg',
					'ti ti-star': 'ph ph-star ph-bold ph-lg',
					'ti ti-star-off': 'ph ph-star-half ph-bold ph-lg',
					'ti ti-sun': 'ph ph-sun ph-bold ph-lg',
					'ti ti-switch-horizontal': 'ph ph-arrows-left-right ph-bold ph-lg',
					'ti ti-terminal-2': 'ph ph-terminal-window ph-bold ph-lg',
					'ti ti-text-caption': 'ph ph-text-indent ph-bold ph-lg',
					'ti ti-tool': 'ph ph-wrench ph-bold ph-lg',
					'ti ti-trash': 'ph ph-trash ph-bold ph-lg',
					'ti ti-trophy': 'ph ph-trophy ph-bold ph-lg',
					'ti ti-universe': 'ph ph-rocket-launch ph-bold ph-lg',
					'ti ti-upload': 'ph ph-upload ph-bold ph-lg',
					'ti ti-user': 'ph ph-user ph-bold ph-lg',
					'ti ti-user-check': 'ph ph-check ph-bold ph-lg',
					'ti ti-user-circle': 'ph ph-user-circle ph-bold ph-lg',
					'ti ti-user-edit': 'ph ph-user-list ph-bold ph-lg',
					'ti ti-user-exclamation': 'ph ph-warning-circle ph-bold ph-lg',
					'ti ti-user-off': 'ph ph-user-minus ph-bold ph-lg',
					'ti ti-user-plus': 'ph ph-user-plus ph-bold ph-lg',
					'ti ti-user-search': 'ph ph-user-circle ph-bold ph-lg',
					'ti ti-user-shield': 'ph ph-newspaper-clipping ph-bold ph-lg',
					'ti ti-users': 'ph ph-users ph-bold ph-lg',
					'ti ti-video': 'ph ph-video ph-bold ph-lg',
					'ti ti-volume': 'ph ph-speaker-high ph-bold ph-lg',
					'ti ti-volume-3': 'ph ph-speaker-x ph-bold ph-lg',
					'ti ti-webhook': 'ph ph-webhooks-logo ph-bold ph-lg',
					'ti ti-whirl': 'ph ph-globe-hemisphere-west ph-bold ph-lg',
					'ti ti-window-maximize': 'ph ph-frame-corners ph-bold ph-lg',
					'ti ti-world': 'ph ph-globe-hemisphere-west ph-bold ph-lg',
					'ti ti-world-download': 'ph ph-cloud-arrow-down ph-bold ph-lg',
					'ti ti-world-search': 'ph ph-binoculars ph-bold ph-lg',
					'ti ti-world-upload': 'ph ph-cloud-arrow-up ph-bold ph-lg',
					'ti ti-world-x': 'ph ph-planet ph-bold ph-lg',
					'ti ti-x': 'ph ph-x ph-bold ph-lg',
 					'ti ti-caret-down': 'ph ph-caret-down ph-bold ph-lg',
 					'ti ti-chevron-down': 'ph ph-caret-down ph-bold ph-lg',
				},
			}),
	];
}
